---
- name: Create vserver
  netapp.ontap.na_ontap_svm:
    state: "{{ item.state }}"
    name: "{{ item.name }}"
    root_volume: "{{ item.root_volume_aggr }}"
    root_volume_aggregate: "{{ item.root_volume_aggr }}"
    root_volume_security_style: "{{ item.security_style }}"
    aggr_list: "{{ item.aggr_list }}"
    allowed_protocols: "{{ item.allowed_protocols }}"
    ipspace: "{{ item.ipspace }}"
    hostname: "{{ item.ntap_hostname }}"
    username: "{{ item.ntap_username }}"
    password: "{{ item.ntap_password }}"
    https: "{{ https }}"
    validate_certs: "{{ certs }}"
  connection: local


